name: Horusec Security Scan

on:
  push:
    branches: [dev]

jobs:
  horusec-security:
    name: Run Horusec Security Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Install Horusec CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta
        horusec version

    - name: Run Horusec scan
      run: |
        horusec start -p="./" -o="sarif" -O="horusec-results.sarif"
    
    - name: Upload Horusec result
      uses: actions/upload-artifact@v4
      with:
        name: horusec-result
        path: horusec-results.sarif
            
    - name: Upload Horusec scan to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: horusec-results.sarif
